DROP TABLE IF EXISTS TABLE3;
CREATE TABLE TABLE3
(
    ID               INT PRIMARY KEY,
    COLUMN_CHAR      CHAR(10),
    COLUMN_VARCHAR   VARCHAR(100),
    COLUMN_NUMBER    DECIMAL(10,2),
    COLUMN_DATE      DATE,
    COLUMN_TIME TIME NULL DEFAULT NULL
);
