DROP TABLE IF EXISTS TABLE1;
CREATE TABLE TABLE1
(
    ID               INT PRIMARY KEY,
    COLUMN_CHAR      CHAR(10),
    COLUMN_VARCHAR   VARCHAR(100),
    COLUMN_NUMBER    DECIMAL(10,2),
    COLUMN_DATE      DATE,
    COLUMN_TIME TIME NULL DEFAULT NULL
);

DROP TABLE IF EXISTS TABLE2;
CREATE TABLE TABLE2
(
    ID               INT PRIMARY KEY,
    COLUMN_CHAR      CHAR(10),
    COLUMN_VARCHAR   VARCHAR(100),
    COLUMN_NUMBER    DECIMAL(10,2),
    COLUMN_DATE      DATE,
    COLUMN_TIME TIME NULL DEFAULT NULL
);
